# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "sg"
  ];
  boot.extraModulePackages = [ ];

  # main-pool is a 3-disk btrfs array managed outside of disko
  fileSystems."/mnt/main-pool" = {
    device = "/dev/disk/by-label/main-pool";
    fsType = "btrfs";
  };

  # Swapfile on the root btrfs subvolume (btrfs requires chattr +C, handled by NixOS)
  swapDevices = [
    {
      device = "/swapfile";
      size = 20480;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
