# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/333b1c2c-db0d-4d01-bb48-06d70d3b69a9";
    fsType = "btrfs";
    options = [
      "subvol=@nixos"
      "autodefrag"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/333b1c2c-db0d-4d01-bb48-06d70d3b69a9";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "autodefrag"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/333b1c2c-db0d-4d01-bb48-06d70d3b69a9";
    fsType = "btrfs";
    options = [
      "subvol=@games"
      "autodefrag"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E61A-6632";
    fsType = "vfat";
  };

  fileSystems."/mnt/extra/games" = {
    device = "/dev/disk/by-uuid/6e625a88-27a8-490d-8179-486ca0fccae3";
    fsType = "btrfs";
    options = [
      "subvol=games"
      "autodefrag"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/extra/media" = {
    device = "/dev/disk/by-uuid/6e625a88-27a8-490d-8179-486ca0fccae3";
    fsType = "btrfs";
    options = [
      "subvol=media"
      "autodefrag"
      "noatime"
      "compress=zstd"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/79744317-a269-4ad8-b201-889e7e146b6e"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
