# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  fileSystems."/home/jeffrey/harmon_family_game_servers" =
    {
      device = "/dev/disk/by-uuid/d5b98bf1-66c2-47c4-87d1-a91dca223706";
      fsType = "btrfs";
      options = [ "subvol=harmon_family_game_servers" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.cni0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker_gwbridge.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth008292c3.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1589e001.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth45bedcd6.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth485dfb92.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth65c8be31.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth91057314.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethbd34d4bc.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe20ecf6d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetheb18132f.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
